# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/2018.3/myworkplace/cjm_fa_useip/cjm_fa_useip.srcs/sources_1/ip/halfadder_0/halfadder_0.xci
# IP: The module: 'halfadder_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/2018.3/myworkplace/Vivado/2018.3/myworkplace/halfadder/halfadder.srcs/constrs_1/new/con_halfadder.xdc
# XDC: The top module name and the constraint reference have the same name: 'halfadder_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado/2018.3/myworkplace/cjm_fa_useip/cjm_fa_useip.srcs/sources_1/ip/halfadder_0/halfadder_0.xci
# IP: The module: 'halfadder_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/2018.3/myworkplace/Vivado/2018.3/myworkplace/halfadder/halfadder.srcs/constrs_1/new/con_halfadder.xdc
# XDC: The top module name and the constraint reference have the same name: 'halfadder_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
